### ISSUE TITLE
[Question] Reboot instance

### ISSUE THREAD

**Issue by floydwch** [duguyue100/awsdlgpu#1]
Hi,

Thanks for your nice walkthrough, I'm struggling to make the GPU work, following this post [How to install Theano on Amazon EC2 GPU instances for deep learning](http://markus.com/install-theano-on-aws/) first, but my Theano still complains the driver issue.

Your solution seems to comprehensive but I want to know the effect of `Reboot your instance by stopping and starting it`, do you mean the simple `sudo reboot` won't work?

Since I was working on spot instance, it can't restart anyway...

Thanks.

**Comment by duguyue100** [comment]
Hi,

actually in the latest setup I've done, `reboot` is actually working. so you can use it without trouble.

Actually, it's better to use Anaconda to get your theano support instead of hand-install everything.

And I think you can find my public image at Singapore region. Please use that.
Do remember that all your support of python in my public image is from Anaconda instead of system's python distribution.

Regards,
Hu Yuhuang.

**Comment by floydwch** [comment]
Thanks for your AMI, I've tried but it seems to fail if I change the SSD volume to a lower size, i.e. 60G.

I finally got things done refer to [Caffe on EC2 Ubuntu 14.04 Cuda 7](https://github.com/BVLC/caffe/wiki/Caffe-on-EC2-Ubuntu-14.04-Cuda-7), but still thank you for your tips.
